name: Build and Test

on:
  push:
    branches:
      - "develop"
      - "feature/*"
      - "bugfix/*"
  pull_request:
    branches:
      - "main"
      - "develop"

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: Setup - Checkout code
        uses: actions/checkout@v4

      - name: Setup - Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup - Install Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v2

      - name: Setup - Show Chrome version
        run: ${{ steps.setup-chrome.outputs.chrome-path }} --version

      - name: Build - Install dependencies
        run: npm ci

      - name: Build - Run tests
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

      - name: Build - Compile Angular app
        run: npm run build -- --configuration=production
